### ISSUE TITLE
Error: Could not find file: 'graphql.d.ts'

### ISSUE THREAD

**Issue by hongbo-miao** [kamilkisiela/universal-starter-apollo#3]
Hi @kamilkisiela this starter right now gives the error when start.

```
/universal-starter-apollo/node_modules/typescript/lib/typescript.js:55145
                throw new Error("Could not find file: '" + fileName + "'.");
                      ^
Error: Could not find file: '/universal-starter-apollo/node_modules/graphql-tools/node_modules/typed-graphql/graphql.d.ts'.
    at getValidSourceFile (/universal-starter-apollo/node_modules/typescript/lib/typescript.js:55145:23)
    at Object.getSyntacticDiagnostics (/universal-starter-apollo/node_modules/typescript/lib/typescript.js:55346:52)
    at /universal-starter-apollo/node_modules/ts-loader/index.js:332:42
    at Array.forEach (native)
    at Compiler.<anonymous> (/universal-starter-apollo/node_modules/ts-loader/index.js:331:14)
    at next (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/CachePlugin.js:61:4)
    at Compiler.applyPluginsAsync (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compiler.js:471:10)
    at Compilation.applyPluginsAsync (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compilation.js:626:18)
    at Compilation.applyPluginsAsync (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compilation.js:617:10)
    at Compilation.applyPluginsAsync (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compilation.js:612:9)
    at Compilation.applyPluginsAsync (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compilation.js:608:8)
    at Compilation.applyPluginsAsync (/universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:73:70)
    at Compilation.seal (/universal-starter-apollo/node_modules/webpack/lib/Compilation.js:554:7)
    at Compiler.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compiler.js:468:16)
    at /universal-starter-apollo/node_modules/webpack/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/universal-starter-apollo/node_modules/webpack/lib/Compilation.js:452:10)
    at /universal-starter-apollo/node_modules/webpack/lib/Compilation.js:423:12
    at /universal-starter-apollo/node_modules/webpack/lib/Compilation.js:335:10
    at /universal-starter-apollo/node_modules/async/lib/async.js:52:16
    at done (/universal-starter-apollo/node_modules/async/lib/async.js:246:17)
    at /universal-starter-apollo/node_modules/async/lib/async.js:44:16
    at /universal-starter-apollo/node_modules/webpack/lib/Compilation.js:335:10
    at /universal-starter-apollo/node_modules/async/lib/async.js:52:16
    at done (/universal-starter-apollo/node_modules/async/lib/async.js:246:17)
```

**Comment by kamilkisiela** [comment]
Check my recent changes to see if it works :)

**Comment by hongbo-miao** [comment]
Cool, works again!
